MyBookStore/MyBookStore/Models/BookModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using MyBookStore.Enums;
using MyBookStore.Helpers;
using Microsoft.AspNetCore.Http;

namespace MyBookStore.Models
{
    public class BookModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please Enter the Title of your book")]
        [StringLength(100, MinimumLength = 5, ErrorMessage = "Title length must be between 5 to 100 characters")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Please Enter the Author name")]
        public string Author { get; set; }

        [StringLength(500)]
        public string Description { get; set; }

        public string Category { get; set; }

        [Required(ErrorMessage = "Please select Language of your book")]
        public int LanguageId { get; set; }

        [Required(ErrorMessage = "Please Enter the Total Pages")]
        [Display(Name = "Total Pages Of Book")]
        public int? TotalPages { get; set; }

        public string Language { get; set; }

        [Required(ErrorMessage = "Please Choose the cover photo of your book")]
        [Display(Name = "Cover photo of your book")]
        public IFormFile CoverPhoto { get; set; }

        public string CoverImageUrl { get; set; }

        [Required(ErrorMessage = "Please Choose the gallery images of your book")]
        [Display(Name = "Choose the gallery images of your book")]
        public IFormFileCollection GalleryFiles { get; set; }

        public List<GalleryModel> Gallery { get; set;  }

        [Required(ErrorMessage = "Please Upload the book in PDF format")]
        [Display(Name = "Upload the book in PDF format")]
        public IFormFile BookPdf { get; set; }

        public string BookpdfUrl { get; set; }
    }
}

MyBookStore/MyBookStore/Models/GalleryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBookStore.Models
{
    public class GalleryModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string URL { get; set; }
    }
}

MyBookStore/MyBookStore/Models/LanguageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBookStore.Models
{
    public class LanguageModel
    {
        public int Id { get; set; }

        public string Text { get; set; }
    }
}

MyBookStore/MyBookStore/Components/TopBooksViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyBookStore.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBookStore.Components
{
    public class TopBooksViewComponent : ViewComponent
    {
        private readonly BookRepository _bookRepository;

        public TopBooksViewComponent(BookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync(int count)
        {
            var books = await _bookRepository.GetTopBooksAsync(count);
            return View(books);
        }
    }
}

MyBookStore/MyBookStore/Controllers/BookController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyBookStore.Models;
using MyBookStore.Repository;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MyBookStore.Controllers
{
    public class BookController : Controller
    {
        private readonly BookRepository _bookRepository = null; 
        private readonly LanguageRepository _languageRepository = null;
        private readonly IWebHostEnvironment _webHostEnvironment = null;

        public BookController(BookRepository bookRepository, LanguageRepository languageRepository, IWebHostEnvironment webHostEnvironment)
        {
            _bookRepository = bookRepository;
            _languageRepository = languageRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<ViewResult> GetAllBooks()
        {
            var data = await _bookRepository.GetAllBooks();

            return View(data);
        }

        public async Task<ViewResult> GetBookById(int id)
        {
            var data = await _bookRepository.GetBookById(id);
            return View(data);
        }

        public List<BookModel> SearchBooks(string bookName, string authorName)
        {
            return _bookRepository.SearchBook(bookName, authorName);
        }

        public async Task<ViewResult> AddNewBook(bool isSuccess = false, int bookId = 0)
        {
            ViewBag.Language = new SelectList(await _languageRepository.GetLanguage(), "Id", "Name") ;
            ViewBag.isSuccess = isSuccess;
            ViewBag.BookId = bookId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddNewBook(BookModel bookModel)
        {
            if (ModelState.IsValid)
            {
                if (bookModel.CoverPhoto != null)
                {
                    string folder = "books/cover/";
                    bookModel.CoverImageUrl = await UploadImage(folder, bookModel.CoverPhoto);
                }

                if (bookModel.GalleryFiles != null)
                {
                    bookModel.Gallery = new List<GalleryModel>();
                    string folder = "books/gallery/";
                    foreach (var file in bookModel.GalleryFiles)
                    {
                        var gallery = new GalleryModel()
                        {
                            Name = file.FileName,
                            URL = await UploadImage(folder, file),
                        };
                        bookModel.Gallery.Add(gallery);
                    }
                    bookModel.CoverImageUrl = await UploadImage(folder, bookModel.CoverPhoto);
                }

                if (bookModel.BookPdf != null)
                {
                    string folder = "books/pdf/";
                    bookModel.BookpdfUrl = await UploadPDF(folder, bookModel.BookPdf);
                }

                int id = await _bookRepository.AddNewBook(bookModel);
                if (id > 0)
                {
                    return RedirectToAction("AddNewBook", new { isSuccess = true, bookId = id });
                }
            }
            ViewBag.Language = new SelectList(await _languageRepository.GetLanguage(), "Id", "Name");
            return View();
        }

        private async Task<string> UploadImage(string folderPath, IFormFile file)
        {
            folderPath += Guid.NewGuid().ToString() + "_" + file.FileName;
            string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folderPath);
            await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
            return "/" + folderPath;
        }

        private async Task<string> UploadPDF(string folderPath, IFormFile file)
        {
            folderPath += Guid.NewGuid().ToString() + "_" + file.FileName;
            string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folderPath);
            await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
            return "/" + folderPath;
        }
    }
}

MyBookStore/MyBookStore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Dynamic;
using MyBookStore.Models;

namespace MyBookStore.Controllers
{
    public class HomeController : Controller
    {
        public ViewResult Index()
        {
            return View();
            
            //return View("AboutUs");
            //Full Path
            //return View("TempView/Index.cshtml");
            //return View("~/TempView/Index.cshtml");
            //Relative Path
            //return View("../../TempView/Index");
        }

        public ViewResult AboutUs()
        {
            return View();
        }

        public ViewResult ContactUs()
        {
            return View();
        }
    }
}

MyBookStore/MyBookStore/Views/Book/AddNewBook.cshtml
@using MyBookStore.Enums;
@model BookModel
@{
    ViewData["Title"] = "Add new book";
}
<div class="container">
    <h3 class="display-4">Add new book</h3>
    <hr />
    @if (ViewBag.IsSuccess == true)
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Congratulations</strong> You have added new book successfully. <br />
            Click <a asp-controller="Book" asp-action="GetBookById" asp-route-id="@ViewBag.BookId">here</a> to view the details
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }

<form method="post" enctype="multipart/form-data" asp-action="AddNewBook" asp-controller="Book">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" />
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>

    <div class="form-group">
        <label asp-for="LanguageId"></label>
        <select asp-for="LanguageId" class="form-control" asp-items="ViewBag.Language">
            <option value="">Please Select Language</option>
        </select>
        <span class="text-danger" asp-validation-for="LanguageId"></span>
    </div>

    <div class="form-group">
        <label asp-for="Author"></label>
        <input asp-for="Author" class="form-control" />
        <span class="text-danger" asp-validation-for="Author"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>

    <div class="form-group">
        <label asp-for="TotalPages"></label>
        <input asp-for="TotalPages" class="form-control" />
        <span class="text-danger" asp-validation-for="TotalPages"></span>
    </div>

    <div class="form-group">
        <label asp-for="CoverPhoto"></label>
        <div class="custom-file">
            <input asp-for="CoverPhoto" class="custom-file-input" id="customFile" />
            <label class="custom-file-label" for="customFile"></label>
        </div>
        <span class="text-danger" asp-validation-for="CoverPhoto"></span>
    </div>

    <div class="form-group">
        <label asp-for="GalleryFiles"></label>
        <div class="custom-file">
            <input asp-for="GalleryFiles" class="custom-file-input" id="customFile" />
            <label class="custom-file-label" for="customFile"></label>
        </div>
        <span class="text-danger" asp-validation-for="GalleryFiles"></span>
    </div>

    <div class="form-group">
        <label asp-for="BookPdf"></label>
        <div class="custom-file">
            <input asp-for="BookPdf" class="custom-file-input" id="customFile" />
            <label class="custom-file-label" for="customFile"></label>
        </div>
        <span class="text-danger" asp-validation-for="BookPdf"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Add book" class="btn btn-primary" />
    </div>
</form>
</div>

MyBookStore/MyBookStore/Views/Book/GetAllBooks.cshtml
@{
    ViewData["title"] = "All Books";
}

@model IEnumerable<BookModel>

<div class="container">
    <h3 class="display-4">All books</h3>
    <div class="row">
        @foreach (var book in Model)
        {
            <div class="col-md-4">
                <partial name="_bookThumbnail" model="@book" />
            </div>
        }
    </div>
</div>

MyBookStore/MyBookStore/Views/Book/GetBookById.cshtml
@{
    ViewData["title"] = "Details of " + Model.Title + " book";
}
@model BookModel

<div class="container">
    <h3 class="display-4">Book details</h3>
    <div class="row">
        <div class="col-md-6">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    @for (int i = 0; i < Model.Gallery.Count(); i++)
                    {
                        <li data-target="#carouselExampleIndicators" data-slide-to="@i" class="@(i==0 ? "active" : "")"></li>
                    }
                </ol>
                <div class="carousel-inner">
                    @for (int i = 0; i < Model.Gallery.Count(); i++)
                    {
                        <div class="@(i==0 ? "carousel-item active" : "carousel-item")">
                            <img class="d-block w-100" src="@Model.Gallery[i].URL" alt="@Model.Gallery[i].Name">
                        </div>
                    }
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <h1>@Model.Title</h1>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 text-primary">
                    <span class="label label-primary">By: </span>
                    <span class="monospaced">@Model.Author</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <p class="description">
                        @Model.Description
                    </p>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <a class="btn btn-outline-primary" data-toggle="modal" data-target="#bookModel">Read now</a>
                </div>
            </div>

            <hr />

            <ul class="list-group">
                <li class="list-group-item"><span class="font-weight-bold">Category - </span> @Model.Category</li>
                <li class="list-group-item"><span class="font-weight-bold">Total pages - </span> @Model.TotalPages</li>
                <li class="list-group-item"><span class="font-weight-bold">Language - </span> @Model.Language</li>
            </ul>
        </div>
    </div>

    <div class="modal fade" id="bookModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">@Model.Title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <embed src="@Model.BookpdfUrl" class="w-100" />
                    @*<iframe src="@Model.BookpdfUrl" class="w-100"></iframe>*@
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <hr />

    <div class="py-5 bg-light">
        <h3 class="h3">Similar books</h3>
        <div class="row">
            @for (int i = 0; i < 5; i++)
            {
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                        <div class="card-body">
                            <h3 class="card-title">book.Title</h3>
                            <p class="card-text">book.Description</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="#" class="btn btn-sm btn-outline-secondary">View details</a>
                                </div>
                                <small class="text-muted">book.Author</small>
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>

MyBookStore/MyBookStore/Views/Home/AboutUs.cshtml
@{
    ViewData["title"] = "About Us";
}
<h1>About Page Of the Book Store</h1>

MyBookStore/MyBookStore/Views/Home/ContactUs.cshtml
@{
    ViewData["title"] = "Contact Us";
}
<h1>Contact Us</h1>

MyBookStore/MyBookStore/Views/Home/Index.cshtml
@{
    ViewData["title"] = "Home";
}
<section class="jumbotron text-center">
    <div class="container">
        <h1>Welcome to Book Store</h1>
        <p class="lead text-muted">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        </p>
        <p>
            <a href="#" class="btn btn-primary my-2">Search Books</a>
        </p>
    </div>
</section>

<div class="py-5 bg-light">
    <div class="container">
        <h3 class="h3">Top books</h3>

        @await Component.InvokeAsync("TopBooks", new { count = 4 })

        @*<vc:top-books count="3"></vc:top-books>*@
    </div>
</div>

MyBookStore/MyBookStore/Views/Shared/Components/TopBooks/Default.cshtml
@model IEnumerable<BookModel>

<div class="row">
    @foreach (var book in Model)
    {
        <div class="col-md-4">
            <partial name="_bookThumbnail" model="book" />
        </div>
    }

</div>

MyBookStore/MyBookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["title"] | Book Store App</title>
    <environment include="Development">
        <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    </environment>
    <link href="~/css/Site.css" rel="stylesheet" />
</head>
<body>
    <partial name="_header" />

    <main role="main">
        @RenderBody()
    </main>

    <partial name="_footer" />

    <environment include="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/jquery-validate/jquery.validate.js"></script>
        <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/jquery.min.js"></script>
        <script src="~/jquery-validate/jquery.validate.min.js"></script>
        <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    </environment>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

MyBookStore/MyBookStore/Views/Shared/_bookThumbnail.cshtml
@model BookModel

<div class="card mb-4 shadow-sm">
    <img src="@(string.IsNullOrEmpty(Model.CoverImageUrl) ? "/images/noimage.png" : Model.CoverImageUrl)" class="img-thumbnail" />
    <div class="card-body">
        <h3 class="card-title">@(string.IsNullOrEmpty(Model.Title) ? "Name is not available" : Model.Title)</h3>
        <p class="card-text">@(string.IsNullOrEmpty(Model.Description) ? "Description is not availabe": Model.Description)</p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <a asp-controller="Book" asp-action="GetBookById" asp-route-id="@Model.Id" class="btn btn-sm btn-outline-secondary">View details</a>
            </div>
            <small class="text-muted">@(string.IsNullOrEmpty(Model.Author) ? "NA" : Model.Author)</small>
        </div>
    </div>
</div>

MyBookStore/MyBookStore/Views/Shared/_footer.cshtml
<footer class="border-top footer text-muted text-center">
    <div class="container">
        Copyright  &copy; Book Store @DateTime.Now.Year
        @*<custom-email my-email="dhavalrakholiya5@gmail.com"></custom-email>*@
    </div>
</footer>

MyBookStore/MyBookStore/Views/Shared/_header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="~/images/logo.png" width="30" height="30" />
                Book store
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="btn btn-outline-primary">Login</a>
                        <a class="btn btn-primary">Register</a>
                    </li>
                </ul>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="AboutUs">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="ContactUs">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Book" asp-action="GetAllBooks">All Books</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Book" asp-action="AddNewBook">Add new book</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>